package com.thechase.domain.models

enum class GameAction {

    START,
    SHOW_PLAYER_ANSWER,
    SHOW_CHASER_ANSWER,
    SHOW_RIGHT_ANSWER,
    MOVE_PLAYER,
    MOVE_PLAYER_BACK,
    MOVE_CHASER,
    MOVE_CHASER_BACK,
    NEXT_QUESTION,
    CHANGE_PLAYER,
    PLAY_INTRO,
    START_FINAL,
    ADD_CHASER_FINAL_POINT,
    ADD_PLAYER_FINAL_POINT,
    REMOVE_CHASER_FINAL_POINT,
    REMOVE_PLAYER_FINAL_POINT,
    PAUSE_FINAL_TIMER,
    RESUME_FINAL_TIMER,
    RESET_FINAL_TIMER,
}
